language: python
addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver

install:
  - pip install -e .
  - pip install codecov pytest-cov selenium python-Levenshtein
script:
  - pytest --cov=src tests
after_success:
  - codecov
